blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/forcedotcom/mcp/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
